import '@mantine/core/styles.css';
import { 
  AppShell,
  Text, 
  ColorSchemeScript, 
  Flex, 
  MantineProvider, 
  Space,
  MantineBreakpoint,
} from '@mantine/core';

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from '@/stories/Navbar';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,Blogs,Schedule}:{
  children: React.ReactNode,
  Blogs: React.ReactNode,
  Schedule: React.ReactNode
}) {


  return (
    <html lang="ja">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        {/* <ConvexClientProvider> */}
          <MantineProvider>
          <Navbar />
          <Space h="xl" />
              <Flex 
                mih={50}
                miw={75}
                gap={50}
                justify="center"
                align="center"
                direction="row"
                wrap="wrap">
                <div>{Blogs}</div>
                <div>{Schedule}</div>
              </Flex>
              {children}
          </MantineProvider>
        {/* </ConvexClientProvider> */}
      </body>
    </html>
  );
}
